version: '3.3'

services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HOST_NGINX_PORT}:${DEFAULT_NGINX_PORT}
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - mariadb
    environment:
      XDEBUG_CONFIG: remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      PHP_IDE_CONFIG: serverName=Docker
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  composer:
    build: ./docker/composer
    depends_on:
      - mariadb
    volumes:
      - ./src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    environment:
      XDEBUG_CONFIG: remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      PHP_IDE_CONFIG: serverName=Docker
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  tests:
    build: ./docker/composer
    depends_on:
      - mariadb
    volumes:
      - ./src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    entrypoint: ./vendor/bin/phpunit
#    command: ['tests']
    environment:
      XDEBUG_CONFIG: remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST}
      PHP_IDE_CONFIG: serverName=Docker
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  db_data: {}
